version: "3.8"
services:
  stock-service:
    build: ./backend/stock-service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/stock-service/.env

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - stock-service
    environment:
      - STOCK_SERVICE_URL=http://stock-service:3001
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api-gateway

