name: Backend CI

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Linting for Backend
        run: npm run lint
        working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests for Backend
        run: npm test
        working-directory: ./backend
