name: Frontend CI

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any push to feature branches
      - 'develop'    # Also trigger on pushes to develop branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'  

      - name: Install dependencies for Frontend
        run: npm install
        working-directory: ./frontend  # Adjust the path to your frontend directory

      - name: Run Linting for Frontend
        run: npm run lint
        working-directory: ./frontend  # Linting for frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'

      - name: Install dependencies for Frontend
        run: npm install
        working-directory: ./frontend  # Install frontend dependencies

      # Generate test reports only (no coverage)
      - name: Run Tests with Reports
        run: npm run test:report
        working-directory: ./frontend
        
      # Upload test reports as artifacts (no coverage)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()  # Run even if tests fail
        with:
          name: frontend-test-reports
          path: frontend/test-reports/
