name: Deploy to Render

on:
  push:
    branches:
      - main
      - feature/deploy-on-cloud
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy Stock Service
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_STOCK_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"
      
      - name: Deploy API Gateway
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_API_GATEWAY_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"

      - name: Deploy Frontend
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"