name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any push to feature branches
      - 'develop'
  pull_request:
    branches:
      - 'main'

jobs:
  trivy_scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.22.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy scan on codebase
        run: trivy fs --severity HIGH,CRITICAL --ignore-unfixed .
