name: Docker Image Vulnerability Scan (Trivy)

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any push to feature branches
      - 'develop'
  pull_request:
    branches:
      - 'main'

jobs:
  trivy_scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-image .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.tar.gz
          tar zxvf trivy_0.22.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy scan on Docker image
        run: trivy image --severity HIGH,CRITICAL --ignore-unfixed my-image
